CREATE TABLE tbl_notice(
nno NUMBER,
aid VARCHAR2(100),
ntitle VARCHAR2(600) NOT NULL,
ncontent VARCHAR2(3000) NOT NULL,
ndate DATE DEFAULT SYSDATE,
nupdateday DATE DEFAULT SYSDATE,
nreadcnt NUMBER DEFAULT 0,
CONSTRAINT pk_notice_nno PRIMARY KEY(nno),
CONSTRAINT fk_admin_aid FOREIGN KEY (aid) REFERENCES tbl_admin(aid) ON DELETE CASCADE
)

CREATE SEQUENCE seq_notice_nno
