CREATE TABLE tbl_qa(
qno NUMBER,
mid VARCHAR2(100),
qtitle VARCHAR2(600) NOT NULL,
qcontent VARCHAR2(3000) NOT NULL,
qdate DATE DEFAULT SYSDATE,
qupdateday DATE DEFAULT SYSDATE,
qreadcnt NUMBER DEFAULT 0,
CONSTRAINT pk_qa_qno PRIMARY KEY(qno),
CONSTRAINT fk_member_mid FOREIGN KEY(mid) REFERENCES tbl_member(mid) ON DELETE CASCADE
)

CREATE SEQUENCE seq_qa_qno

